dataset_type: "language_modeling"  # "language_modeling" for TinyStories, "question_answering" for FairytaleQA
dataset_name: "tinystories"
data_path: "data\\processed\\"
checkpoint_dir: "models\\distilbert_model\\checkpoints\\"
model_name: "distilbert-base-uncased"
model_type: "distilbert"

training:
  batch_size: 16
  epochs: 3
  learning_rate: 5e-5

device: "cuda"  # "cuda" for GPU, "cpu" for CPU
